### ISSUE TITLE
`require(...)` is more readable than `if (...) revert();`

### ISSUE THREAD

**Issue by SCBuergel** [dexDev/DEx.top#5]
Consider changing the `if(...) revert();` pattern into `require(...)` which is more readable (e.g. [here](https://github.com/dexDev/DEx.top/blob/master/smart-contract/dextop.sol#L146))

**Comment by libreoscar** [comment]
We chose `if-revert` for saving a bit of gas than `require()`. But experiments with recent versions of solidity with adequate optimization show that they are taking exactly the same amount of gas. So in the next version of DEx.top smart contract we will be using `require()` instead. Thanks for the suggestion.
